<?php
/**
 * @package Woodkit
* @author Sébastien Chandonay www.seb-c.com / Cyril Tissot www.cyriltissot.com
* License: GPL2
* Text Domain: woodkit
*
* Copyright 2016 Sébastien Chandonay (email : please contact me from my website)
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License, version 2, as
* published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
defined('ABSPATH') or die("Go Away!");

function woodkit_get_fonticons_set () {
	static $fonticons_set = -1;
	if ($fonticons_set == -1) {
		$fonticons_set = array();
		
		/** Load classic JSONs */
		$json_files = apply_filters('woodkit_fonticons_set_files', array('dashicons' => WOODKIT_PLUGIN_PATH.WOODKIT_PLUGIN_TEMPLATES_FONTS_FOLDER.'dashicons/icons.json'));
		if (!empty($json_files)) {
			foreach ($json_files as $json_file_slug => $json_file) {
				$json_file_content = file_get_contents($json_file);
				if ($json_file_content) {
					$json = json_decode($json_file_content, true);
					if ($json) {
						if ($json_file_slug == 'fontawesome') {
							$fonticons_set[] = woodkit_parse_fontawesome_icons_json($json);
						} else {
							$fonticons_set[] = $json;
						}
					}
				}
			}
		}
		
		/** FontAwesome specific icons.json (generated by FontAwesome and we don't want to modify it) */
		// TODO
	}
	return $fonticons_set;
}

function woodkit_parse_fontawesome_icons_json ($json) {
	$res = array();
	if ($json) {
		
	}
	return $res;
}
